### ISSUE TITLE
Time stamp on light values invalid

### ISSUE THREAD

**Issue by tiimoS** [Thingy-project-red/thingy-api-red#1]
**STR:** 
- GET Request: http://localhost:8000/api/v1/Thingy1/light_intensity

**ER:** 
[
    {
        "time": "2018-11-01T15:48:05.529Z,
        "blue": 2664,
        "clear": 401,
        "green": 2511,
        "red": 2570
    }
]
light object in the format above with a valid time stamp indicating the time the values were recorded. 

**AR:** 
[
    {
        "time": "**1970-01-01T00:00:00.000Z**",
        "blue": 2663,
        "clear": 394,
        "green": 2500,
        "red": 2575
    }
]
Time stamp is invalid and the same for every light object returned.

**Comment by martindisch** [comment]
It's an issue with the `LAST(*)` function, which only behaves exactly like `*` (fetching all the right fields) when the measurement only has one other field besides the timestamp.
Because of this, the issue is also present for air_quality.

See https://github.com/influxdata/docs.influxdata.com/issues/1095#issue-220727990.

I'm working on it.
